TypeError: only integer scalar arrays can be converted to a scalar index Traceback (most recent call last):   File "C:\Users\2020e\PycharmProjects\AccCam\DSP_CUDA\plotters.py", line 310, in run     line.setData(self.x_data, self.y_data[channel])
    WIP